### ISSUE TITLE
Bug nos tamanhos das divs

### ISSUE THREAD

**Issue by Mr-Saxobeat** [Mr-Saxobeat/iec-site#28]
* A coluna do painel de seleção de dados à esquerda da tela fica com tamanhos variados dependendo da categoria de dados selecionada. Ao selecionar a categoria de Reanálise o mapa sobrepõe o gráfico e o gráfico sobrepõe o painel.
![bug-iec](https://user-images.githubusercontent.com/21086405/107998401-cfc48200-6fc3-11eb-8bb5-23c610080b2c.png)

**Comment by avoxx** [comment]
> Ao selecionar a categoria de Reanálise o mapa sobrepõe o gráfico e o gráfico sobrepõe o painel.

Problema solucionado no pull request.
